### ISSUE TITLE
[Event Request] Codeunit 304 "No. Series - Impl." - OnNoSeriesLineFilterOnBeforeFindLast

### ISSUE THREAD

**Issue by TNMers** [microsoft/ALAppExtensions#26413] opened 2024-05-03 08:09 UTC
### Describe the request

Hello, could you please add an event in function GetNoSeriesLine with the handled-pattern:

```
[InherentPermissions(PermissionObjectType::TableData, Database::"No. Series Line", 'm')]
    procedure GetNoSeriesLine(var NoSeriesLine: Record "No. Series Line"; NoSeriesCode: Code[20]; UsageDate: Date; HideErrorsAndWarnings: Boolean): Boolean
    var
        NoSeriesRec: Record "No. Series";
        NoSeries: Codeunit "No. Series";
        NoSeriesErrorsImpl: Codeunit "No. Series - Errors Impl.";
#if not CLEAN24
#pragma warning disable AL0432
        NoSeriesManagement: Codeunit NoSeriesManagement;
#pragma warning restore AL0432
#endif
        LineFound: Boolean;
    begin
        if UsageDate = 0D then
            UsageDate := WorkDate();

        // Find the No. Series Line closest to the usage date
        NoSeriesLine.Reset();
        NoSeriesLine.SetCurrentKey("Series Code", "Starting Date");
        NoSeriesLine.SetRange("Series Code", NoSeriesCode);
        NoSeriesLine.SetRange("Starting Date", 0D, UsageDate);
        NoSeriesLine.SetRange(Open, true);
        if (NoSeriesLine."Line No." <> 0) and (NoSeriesLine."Series Code" = NoSeriesCode) then begin
            NoSeriesLine.SetRange("Line No.", NoSeriesLine."Line No.");
#if not CLEAN24
#pragma warning disable AL0432
            NoSeriesManagement.RaiseObsoleteOnNoSeriesLineFilterOnBeforeFindLast(NoSeriesLine);
#pragma warning restore AL0432
#endif
            LineFound := NoSeriesLine.FindLast();
            if not LineFound then
                NoSeriesLine.SetRange("Line No.");
        end;
#if not CLEAN24
#pragma warning disable AL0432
        if not LineFound then begin
            NoSeriesManagement.RaiseObsoleteOnNoSeriesLineFilterOnBeforeFindLast(NoSeriesLine);
            LineFound := NoSeriesLine.FindLast();
        end;
#pragma warning restore AL0432
#else
        if not LineFound then
            LineFound := NoSeriesLine.FindLast();
#endif

```

Event definition

```
[EventSubscriber(ObjectType::Codeunit, codeunit::NoSeriesManagement, 'OnNoSeriesLineFilterOnBeforeFindLast', '', false, false)]
    local procedure NoSeriesManagement_OnNoSeriesLineFilterOnBeforeFindLast(var NoSeriesLine: Record "No. Series Line")
```

### Additional context

Compiler Warning AL0432
Internal work item: [AB#538705](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538705)

**Comment by pri-kise** [comment] 2024-05-10 06:49
Could you please outline why you need this event?

The IsHandled events where remove intentionally by @AndreasMoth in this PR https://github.com/microsoft/BCApps/pull/319

There he asked for Feedback on this PR.
Further this object is now internal and the event would have to be add in the facade codeunit

**Comment by grobyns** [comment] 2024-06-26 10:48
This request is very similar to this one here: https://github.com/microsoft/BCApps/issues/1362
For System Application and Business Foundation (and anything else already on BCApps) I'd recommend following the process there: Create an issue, when approved create a PR. Yes it's a little more work on your end but the lead time to a fix should be much shorter.

As this seems like a duplicate of the issue on BCApps i'll close this one.

**Closed by grobyns** 2024-06-26 10:48 UTC
Labels: event-request, Integration
