### ISSUE TITLE
RefreshOnActivate in "Assembly Orders" page (902)

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#17551] opened 2022-05-02 12:48 UTC
We have extended the page "Assembly Orders" with the property StyleExpr in some fields, to print different styles depending some status. Similar than the Status of the "Sales Order List".
But in some cases if we enter into the card, change something and return to the list, the style is not correctly updated.

We request to add the property **RefreshOnActivate = true;** in page 902 "Assembly Orders" as it works for example in the page 9305 "Sales Order List", because we cannot update this property in the PageExtension.

**Comment by AlexanderYakunin** [comment] 2022-05-13 04:53
Duplicate of #17516

**Closed by AlexanderYakunin** 2022-05-13 04:53 UTC
Labels: extensibility-bug
