### ISSUE TITLE
Improvements for "XMLPort Export Generic CSV"

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/ALAppExtensions#5477] opened 2020-01-07 13:32 UTC
Hey together,

hope this is the right place to post this issue here ("For collaboration on system and base applications as well as event requests, use ALAppExtensions.") (https://github.com/Microsoft/AL).  Otherwise, can you tell me what would be the right way?

**Goal**
The above-mentioned XMLPort is good for using it in combination with the Data Exchange Framework. We simply want to export a csv file that is defined by the Data Exchange Definition.

**Problem**
1. The XMLPort does not consider the set up "Column Separator" by the Data Exchange Definition. 2. Moreover, it does consider the _GetValue()_ method from the Table Data Exchange Field.

Just compare the XMLPort to the XMLPort "Data Exch. Import - CSV" that is the pendant to it.

At the moment I created a copy of this XMLPort, but would like to have it in the Base Application itself.

Greetings
Andreas

**Comment by dtkb** [comment] 2020-10-22 15:52
Yes, please.

We also need to be able to change/override the `FieldDelimiter`, initially just via hard-coding all exports should suffice for the current client, but ideally by adding this to the Data Exch Def and getting it from there. I will be opening a new request for that event.

**Comment by JesperSchulz** [comment] 2021-05-18 11:59
Hi!

This rather old case just came flying to my desk, after having been touring around for more than a year :-O The problem is, that this isn't really an extensibility request/defect, but rather a small feature request (normally to be logged on aka.ms/bcideas). It hence doesn't really qualify to be processed as a GitHub issue. However, @AndreasGloeckner, you mention you have a working version of that XMLPort already, but would like it to be part of the Base Application. Would you like to contribute your code to the BaseApp? We don't really have any process for that right now, but maybe we could work something out ad-hoc for this case. Code contribution _is_ part of this repository, and in that case, I could see what we can do :-)

**Comment by AndreasGloeckner** [comment] 2021-06-08 07:13
Hi Jesper,

I would really like to contribute but I don't have the object anymore. I think it was more or less a copy of the "import generic csv".

Sorry, for that.

**Comment by JesperSchulz** [comment] 2021-06-08 10:19
No worries :-) I'll see what I can do!

**Comment by JesperSchulz** [comment] 2021-07-07 08:22
Received confirmation that this should get logged as an idea on [aka.ms/bcideas](http://aka.ms/bcideas). Reason again being, that this is not an extensibility request or related to extensibility, but that it appears to be a request for a tiny feature. If you would provide the object, I would happily put it into the BaseApp, but we cannot process this request as a GitHub issue (prioritization and all, you know...). Closing this issue and hoping to see this reappear as an idea :-)

**Closed by JesperSchulz** 2021-07-07 08:22 UTC
Labels: extensibility-bug
