### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnApplyCustLedgEntryOnBeforeUnrealizedVAT

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26842] opened 2024-07-15 09:30 UTC
### Describe the request

Hello, can you please add a new Event OnApplyCustLedgEntryOnBeforeUnrealizedVAT in Codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure ApplyCustLedgEntry(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Cust: Record Customer)
.
.
.
        NewCVLedgEntryBuf."Applies-to ID" := '';
        NewCVLedgEntryBuf."Amount to Apply" := 0;

        ShouldUpdateCalcInterest := not NewCVLedgEntryBuf.Open;
        OnApplyCustLedgEntryOnAfterCalcShouldUpdateCalcInterestFromNewBuf(OldCVLedgEntryBuf, NewCVLedgEntryBuf, Cust, ShouldUpdateCalcInterest);
        if ShouldUpdateCalcInterest then
            UpdateCalcInterest(NewCVLedgEntryBuf);

        IsHandled := false;
        OnApplyCustLedgEntryOnBeforeUnrealizedVAT(NewCVLedgEntryBuf, IsHandled);
        if not IsHandled then
             if GLSetup."Unrealized VAT" or
                (GLSetup."Prepayment Unrealized VAT" and NewCVLedgEntryBuf.Prepayment)
             then
                 if IsNotPayment(NewCVLedgEntryBuf."Document Type") and
                    (NewRemainingAmtBeforeAppln - NewCVLedgEntryBuf."Remaining Amount" <> 0)
                 then begin
                     NewCustLedgEntry.CopyFromCVLedgEntryBuffer(NewCVLedgEntryBuf);
                     CheckUnrealizedCust := true;
                     UnrealizedCustLedgEntry := NewCustLedgEntry;
                     UnrealizedCustLedgEntry.CalcFields("Amount (LCY)", "Original Amt. (LCY)");
                     UnrealizedRemainingAmountCust := NewCustLedgEntry."Remaining Amount" - NewRemainingAmtBeforeAppln;
                 end;

        OnAfterApplyCustLedgEntry(GenJnlLine, NewCVLedgEntryBuf, OldCustLedgEntry, NewRemainingAmtBeforeAppln);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyCustLedgEntryOnBeforeUnrealizedVAT(CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

In some cases we???d like to skip posting the unrealized VAT, and the check ???if IsNotPayment?????? is insufficient for us.
Internal work item: [AB#542070](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542070)

**Comment by AndersLarsenMicrosoft** [comment] 2024-08-09 08:37
duplicate of https://github.com/microsoft/ALAppExtensions/issues/26841

**Closed by AndersLarsenMicrosoft** 2024-08-09 08:37 UTC
Labels: event-request, Finance
