### ISSUE TITLE
[Extensibility Bug] Table 454 "Approval Entry" | Implicit TableRelation (without field reference) will result in errors when used in implicit expansions in API’s.

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#23012] opened 2023-04-18 08:59 UTC
Dear ALAppExtensions team,

Most of our API entities do have the property `ODataKeyFields` set to `SystemId`. This works fine. However, when we send a request to one of those entities with `?$expand=*`. We get an error that the `System ID` field is not valid. Example below: 

```
{
    "error": {
        "code": "Application_FilterErrorException",
        "message": "The filter \"BE00011\" is not valid for the System ID field on the Contact table. Invalid format of GUID string. The correct format of the GUID string is: CDEF7890-ABCD-0123-1234-567890ABCDEF where 0-9, A-F symbolizes hexadecimal digits.  CorrelationId:  a858d37a-d52e-49ba-8598-51bacf108f5f."
    }
}
```

This can easily be solved by explicitly pointing the table relation to the key field of that table. So in case of a `Contact` it would be `Contact."No."` instead of `Contact`. You can see the difference in the property `ReferencedProperty` in the examples below.

```
<NavigationProperty Name="contact" Type="Microsoft.NAV.contact" ContainsTarget="true">
    <ReferentialConstraint Property="contactNo" ReferencedProperty="no" />
</NavigationProperty>
```
```
<NavigationProperty Name="contact" Type="Microsoft.NAV.contact" ContainsTarget="true">
    <ReferentialConstraint Property="contactNo" ReferencedProperty="systemId" />
</NavigationProperty>
```

So on behalf of 4PS I would like to request to change the `TableRelation` property for the field mentioned below. 

```
src/table/ApprovalEntry.Table.al
field(17; "Currency Code"; Code[10])
{
    Caption = 'Currency Code';
-   TableRelation = Currency;
+   TableRelation = Currency.Code;
}
```

I'm sure that there are more tables with implicit table references. Should I asked that in a separate issue or can I add those to this issue as well? 

What do you think?

**Comment by JesperSchulz** [comment] 2023-05-11 12:55
Feel free to add more to this thread. Once you're done, let us know and we'll process this issue. Alternatively, you could join the "BaseApp contribution pilot" and create a PR. Almost easier. I've added you as a contributor in case you're interested.

https://github.com/microsoft/BusinessCentralApps/pulls

**Comment by JesperSchulz** [comment] 2023-05-11 12:56
If you want to make a PR instead, please let me know and I will transfer this issue to the pilot repo and you're good to go!

**Comment by JesperSchulz** [comment] 2023-06-28 08:12
Please let us know how you would like to proceed with this issue. Will you create a PR? Will you add more tables? Should we just process the one?

**Comment by JesperSchulz** [comment] 2023-07-05 08:56
We are looking into, if this could get addressed by the platform. Ideally, we don't want to update thousands of table relations in the app. We will keep posting updates on this issue.

**Comment by nvleeuwen** [comment] 2023-08-04 06:24
Thanks a lot @JesperSchulz. That was also my thought on this issue. Hopefully you can come up with a more elegant solution. Good luck.

**Comment by JesperSchulz** [comment] 2023-09-08 06:49
I received the following reply from our platform team: We were not able to reproduce issue with $expand=* as mentioned here. This example seems more like wrong filter being used somewhere. To resolve it, repro is needed.  As for the suggestion regarding implicit table relations, ReferencedProperty always point to ODataKeyField (if defined) or to the PK. Only condition for navigation property to be created is referencing & when referenced type should match.

**Comment by JesperSchulz** [comment] 2023-12-01 13:52
Closing based on the above.

**Closed by JesperSchulz** 2023-12-01 13:52 UTC
Labels: extensibility-bug
