### ISSUE TITLE
Report Selections event OnBeforeGetEmailBodyCustomer

### ISSUE THREAD

**Issue by twbook** [microsoft/ALAppExtensions#14427] opened 2021-09-23 13:57 UTC
The OnBeforeGetEmailBodyCustomer is not working correct, it returns a false if we have handled it and none of the changes are used.

  IsHandled := false;
    OnBeforeGetEmailBodyCustomer(
        ReportUsage.AsInteger(), RecordVariant, TempBodyReportSelections, CustNo, CustEmailAddress, EmailBodyText, IsHandled);
    if IsHandled then
        exit;

**Comment by dnpb** [comment] 2021-09-23 14:02
dupe of https://github.com/microsoft/ALAppExtensions/issues/14425 which was already moved ;-)

**Comment by JesperSchulz** [comment] 2021-09-27 07:29
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Closed by JesperSchulz** 2021-09-27 07:29 UTC
Labels: event-request, ships-in-future-update
