### ISSUE TITLE
"Array access is not valid for client expressions", page fields

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#26260] opened 2024-04-10 06:35 UTC
### Describe the request

To be able to create at least somewhat generic lists without hundreds of copypasted lines and variables, we would need to be able to have array access in client expressions. Is there a specific reason this works:
```
field(Col1; Col[1])
  {
      CaptionClass = '3,' + GetColumnHeading(LeftMostColumn + 1);
      ToolTip = '-', Locked = true;
      Visible = MaxColumns >= 1;
  }
```

but this (array access) does not?

```
field(Col1; Col[1])
  {
      CaptionClass = '3,' + GetColumnHeading(LeftMostColumn + 1);
      ToolTip = '-', Locked = true;
      StyleExpression = FieldValidated[1];
  }
```

If the caption can be fetched from a function during runtime, and properties such as visibility, style, enabled, can be evaluated from a boolean OR expression, why could they not be taken from an array? 

It would be great to have this for all the modifiable page field properties.

An array we can handle reasonably in a loop, even if we couldn't use a function directly 
```
  trigger OnAfterGetRecord()
  var
      i: Integer;
  begin
      for i := 1 to PAGEMAXCOLUMNS - 1 do
          FieldValidated[1] := GetFieldValidated(i);
  end;

```

### Additional context

Generic code with a loop instead of copypasting hundreds of lines and tens of variables improves quality, makes for better maintainability and readability etc. and this would also make BC a better platform for new solutions.

**Comment by mynjj** [comment] 2024-04-11 08:36
Hi,

I agree, just FYI, the problem is not with the array expressions but with StyleExpr. You can have a look at places like `SalesAnalysisMatrix.Page.al`, `InventoryAnalysisMatrix.Page.al`, `PurchaseAnalysisMatrix.Page.al`. It is solved by using individual variables for each field.

Unfortunately, this repository is only for tracking extensibility requests (through existing AL constructs, i. e. AL events and interfaces), what you ask for is out of this scope.

However this would be great, so I encourage you to bring it up in https://aka.ms/bcideas , where we monitor these kind of requests. Ideas with enough votes get considered for planning in next waves. 

I'll close the issue in this repo.

**Comment by mynjj** [comment] 2024-04-11 08:37
.

**Comment by mynjj** [comment] 2024-04-11 08:37
Closing as not planned.

**Closed by mynjj** 2024-04-11 08:37 UTC
