### ISSUE TITLE
[ERROR TRANSFERFIELDS] codeunit 6620 "Copy Document Mgt." correcting Posted Sales Invoice with Payment Reference

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#23735] opened 2023-06-07 08:29 UTC
Open **page 132 "Posted Sales Invoice"** (with filled Payment Reference field) when we use actions **Correct** or **Create Corrective Credit Memo** following error comes:

The contents of the **Payment Reference** field cannot be copied to the **Received-from Country/Region Code** field because the size of the Received-from Country/Region Code field is too small.

Type: **Code10 <-- Code50**
Field: **Received-from Country/Region Code <-- Payment Reference**
Table: **Sales Header <-- Sales Invoice Header**

Al Call Stack: 
"Copy Document Mgt."(CodeUnit 6620).CopySalesHeaderFromPostedInvoice line 10 - Base Application by Microsoft
"Copy Document Mgt."(CodeUnit 6620).CopySalesDocUpdateHeader line 22 - Base Application by Microsoft
"Copy Document Mgt."(CodeUnit 6620).CopySalesDoc line 66 - Base Application by Microsoft
"Copy Document Mgt."(CodeUnit 6620).CopySalesDocForInvoiceCancelling line 6 - Base Application by Microsoft
"Correct Posted Sales Invoice"(CodeUnit 1303).CreateCopyDocument line 20 - Base Application by Microsoft
"Correct Posted Sales Invoice"(CodeUnit 1303).CreateCreditMemoCopyDocument line 9 - Base Application by Microsoft
"Posted Sales Invoice"(Page 132)."CreateCreditMemo - OnAction"(Trigger) line 11 - Base Application by Microsoft

Places where error comes **codeunit 6620 "Copy Document Mgt."**:
procedure **CopySalesDoc**(FromDocType: Enum "Sales Document Type From"; FromDocNo: Code[20]; var ToSalesHeader: Record "Sales Header")
...
                    "Sales Document Type From"::"Posted Invoice":
                        begin
                            FromSalesHeader.TransferFields(FromSalesInvHeader);
...

local procedure **CopySalesHeaderFromPostedInvoice**(FromSalesInvHeader: Record "Sales Invoice Header"; var ToSalesHeader: Record "Sales Header"; var OldSalesHeader: Record "Sales Header")
...
ToSalesHeader.TransferFields(FromSalesInvHeader, false);
...

    procedure **CopySalesInvLinesToDoc**(ToSalesHeader: Record "Sales Header"; var FromSalesInvLine: Record "Sales Invoice Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
...
FromSalesHeader.TransferFields(FromSalesInvHeader);
...

**Comment by pri-kise** [comment] 2023-06-07 08:50
This repository isn't meant for bug reports.
You should use the common support channels.

See this issue for more details:
Already report to Microsoft and they are working on a bugfix
Duplicate of https://github.com/microsoft/ALAppExtensions/issues/23697

**Comment by AlexanderYakunin** [comment] 2023-06-07 08:56
@OlgicaA - please use technical support to raise urgent issues, or they will be here without proper attention.

**Closed by AlexanderYakunin** 2023-06-07 08:56 UTC
