### ISSUE TITLE
COD1380 -  InsertBatchParameterMapEntry to Global/External

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#2510] opened 2019-05-20 09:14 UTC
Hi,

could you please set the InsertBatchParameterMapEntry in COD1380 to global and external.

Also we would need a function an external function to set a specific BatchID from outside.

Background is, that we would like to add and Redirect posting Parameters.

**Comment by SKeiler** [comment] 2019-05-20 11:13
I would like to add an additional wish. Could the AddParameter-function rebuilded so that it is possible to overwrite an existing parameters? It would be enough to check if there is already an existing Parameter and delete this before insert the new one.

**Comment by RomanZanizdra** [comment] 2019-05-20 13:55
Hi SKeiler.
Does your request have any relation to the bug or the problem you faced? Do you try to resolve any problems with setting a specific BatchID? Or could you describe the scenario you are trying to cover.
I ask because of first, mentioned area will change a little in the nearest time due to some hotfixes, the second I cannot understand what you are going to achieve.

**Comment by SKeiler** [comment] 2019-05-20 14:36
Hi Roman,

do you mean the possibility to set the Batch-ID from outside or do you mean the rebuild of the AddParameter-function?

For the SetBatchID-Procedure: We would like to add new (own) posting parameters from other system parts where we don't have the access to the originial instance of the codeunit (for example directly out of codeunit 80 to read them later in posting process). So we would try to read if there some other parameters recording to the RECORDID and than we would set the BatchID same to the existing processing Parameters BatchID. If there are no existing Batch Processing Parameters, we create a new set (with Batch Processing Parameter and Batch Processing Parameter Map). With pleasure you Can also implement a function which exactly does this). That seems the only way to add parameters subsequently. 

![image](https://user-images.githubusercontent.com/45033081/58028511-2bc25400-7b1b-11e9-8621-8395797dcda9.png)

For the rebuild of the AddParameter-Function: We have the requirement to force the update of the Posting date. In this case we would like to only set the Parameters in the Batch Processing Parameters to replace the Posting Date out of an Event function. Unfortunately in batch Posting this parameters are already set (with the replace Posting date Parameter is set to false) so that we need a possibility to overwrite the Parameter. It would be helpful if the AddParameter-Function could already handle this.

**Comment by RomanZanizdra** [comment] 2019-05-28 14:44
Hi SKeiler. Thanks for your reply. I think I understand what you are asking about AddParameter function, but still don't fully understand about SetBatchId function. Can you describe your case in terms of steps to reproduce, something like user has 5-10 invoices, he posts them all at one time, some of the invoices should be corrected with the new posting date while posting in dependency on some parameters... and so on and so on. Is it acceptable for you, does it make sense?

**Comment by RomanZanizdra** [comment] 2019-06-05 07:26
Hi SKeiler, will you provide any information?

**Comment by SKeiler** [comment] 2019-06-05 07:53
Hi Roman,

today you need the one instance of COD1380 which hold the global BatchID-variable to add a parameter. That's the reason while the instance is copied through the whole batch processing process (for example from Report 296 to Codeunit 1371, than two times to new instances of Codeunit 1371). 

Now we have to targets. 
The first is to add a completly new (own) parameter in Codeunit 80. But that is not possible because if we create a new variable for Codeunit 1371 in Codeunit 80 (or in one of our Event Subscribers), the global BatchID is not set in this new instance. It is possible to read the current BatchID out of TAB53 for the current Sales Header, but there are no possibilities to get this BatchID to the created new instance of Codeunit 1371 in codeunit 80 (or the Event Subscriber) to use the AddParameter-Function. 

The second is, that we want force the update auf the Posting Date to the current Workdate. We book 10 invoices and always want to ensure in COD80, that the Posting Date is set to the last date of the period. But it is not possible to overwrite the replace Posting Date-Parameter in TAB53 by using the existing functions. First the AddParameter-procedure do not allow to overwrite an existing parameter und second it is not possible to set an explicit BatchID in COD1371 (see above).

**Comment by RomanZanizdra** [comment] 2019-06-06 04:56
Hi SKeiler.
You can create your instance of COD1380, add any number of parameters you needed and then pass it to COD1371.

**Comment by RomanZanizdra** [comment] 2019-06-07 07:04
Hi SKeiler. Can we somehow move our discussion to its logical end in order you have some solution from our side or we agree on something? Let's summarize what we have at this moment.
- I think this is not a good idea to have a possibility to set BatchId from any place.
- Agree that Add-Parameter function can update parameter value in the case it already exists.
- If I'm not mistaken you can add any number of your own parameters via Add-Parameter function.
- You can run COD1371 directly if it is needed.
- Still your case is not clear.
a) Do you use MS batch posting solution, fully or partially or just objects for your own solution?
b) Do you need to update parameters of batch posting procedure when you already come into codeunit 80?
c) You didn't answer on the question of your business case, what user is doing? Is this sensitive information you cannot share with me?
SKeiler, I really want to help you to resolve the issue, but cannot do this without information from your side. Please answer the questions so we can move further or close the issue if the theme exhausted.

**Comment by RomanZanizdra** [comment] 2019-06-10 06:50
Hi SKeiler. Any update from side, I plan to close this issue?

**Comment by RomanZanizdra** [comment] 2019-06-17 05:45
Any update?

**Comment by RomanZanizdra** [comment] 2019-06-20 05:27
Let's close it for now. Feel free to reopen issue if you have more details or other input.

**Closed by RomanZanizdra** 2019-06-20 05:27 UTC
Labels: request-for-external
