### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeInsertSummarizedVATOnCalcPmtDiscIfAdjVAT

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5581] opened 2020-01-14 13:31 UTC
Could we please have an event OnBeforeInsertSummarizedVATOnCalcPmtDiscIfAdjVAT in Codeunit 12 in function CalcPmtDiscIfAdjVAT?

Code Example:
            if LastConnectionNo <> 0 then begin
                DtldCVLedgEntryBuf := DtldCVLedgEntryBuf2;
                DtldCVLedgEntryBuf."VAT Amount (LCY)" := -TotalVATAmount;
                DtldCVLedgEntryBuf.InsertDtldCVLedgEntry(DtldCVLedgEntryBuf, NewCVLedgEntryBuf, true);
                // start kvspsa - Event Raiser
                **OnBeforeInsertSummarizedVATOnCalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf, OldCVLedgEntryBuf, DtldCVLedgEntryBuf.Amount, DtldCVLedgEntryBuf."Amount (LCY)");**
                // stop kvspsa
                InsertSummarizedVAT(GenJnlLine);
            end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeInsertSummarizedVATOnCalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; Amount: Decimal; AmountLCY: Decimal);
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment] 2020-01-15 08:53
This is exact duplicate of #5580, closing

**Closed** 2020-05-27 15:02 UTC
Labels: event-request
