### ISSUE TITLE
[Event Request] Codeunit 5700User Setup Managemen "OnGetPurchasesFilterUserSetupManagement"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17801] opened 2022-05-06 09:36 UTC
Can we please get the following event?
```
procedure GetPurchasesFilter(UserCode: Code[50]): Code[10]
    begin
        if not HasGotPurchUserSetup then begin
            CompanyInfo.Get();
            PurchUserRespCenter := CompanyInfo."Responsibility Center";
            UserLocation := CompanyInfo."Location Code";
            if UserSetup.Get(UserCode) and (UserCode <> '') then
                if UserSetup."Purchase Resp. Ctr. Filter" <> '' then
                    PurchUserRespCenter := UserSetup."Purchase Resp. Ctr. Filter";
            OnAfterGetPurchFilter(UserSetup, PurchUserRespCenter);
            HasGotPurchUserSetup := true;
        end;
      //Event Request begin
        OnGetPurchasesFilterUserSetupManagement();
    //Event Request End
        exit(PurchUserRespCenter);
    end;

```
 [IntegrationEvent(false, false)]
    local procedure OnGetPurchasesFilterUserSetupManagement()
    begin
    end;

**Comment by dannoe** [comment] 2022-05-06 10:21
duplicate of https://github.com/microsoft/ALAppExtensions/issues/17800

**Comment by JesperSchulz** [comment] 2022-05-15 18:21
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Closed by JesperSchulz** 2022-05-15 18:21 UTC
Labels: event-request, ships-in-future-update
