### ISSUE TITLE
[Event Request] New event on codeunit 27 "Confirm Management"

### ISSUE THREAD

**Issue by MarenVosskoetter** [microsoft/ALAppExtensions#24925] opened 2023-09-27 13:39 UTC
Hello everyone,

we would like to include an OnBefore-/ and an OnAfter event for the functions GetResponse and GetResponseOrDefault from codeunit 27 "Confirm Management" so that we can check in which transactions confirms are displayed. 

![image](https://github.com/microsoft/ALAppExtensions/assets/146198695/31e6fe23-3575-407c-b02a-e077f237e73a)

Thanks in advance.

**Comment by JesperSchulz** [comment] 2023-11-20 10:22
Why would you need that? Adding events here doesn't make a whole lot of sense. Could you elaborate a bit more for us to understand the scenario you are trying to support?

**Comment by LarsBrune** [comment] 2023-11-23 06:24
Perhaps I can answer your questions.

We have a situation where, for example, a warehouse employee partially posts a warehouse document and leaves the terminal while the process is running to look elsewhere or take a lunch break.
Now we have a setting for whether the remaining document should be deleted after posting, which can be set to never, always or after confirmation. The posting process takes a few seconds and, depending on the setting, a confirm appears asking whether the document should be deleted.
However, the warehouse employee no longer sees this popup and since it was triggered within a transaction, the database is locked.

We would therefore need a way of interacting with commits to log whether the commit was triggered in a transaction and by which process it was called.

With these events, we could check whether a transaction is still active and, if so, log the current call stack to know which process it originated from, so that we are always aware of such situations and can prevent them in advance.

In addition, such an event could be used to adjust the question text and the default button if necessary.

**Comment by JesperSchulz** [comment] 2024-01-23 13:33
We've been discussing this back and forth and have finally landed on the conclusion to reject this event request.

First and foremost, the Confirm Management module is only used in about 50% of the cases where a confirm dialog is invoked. These events would hence only fire half of the time. Subscribing to those events would give a wrong sense of security.

Also, it seems like an anti-pattern to introduce generic events for specific purposes. If we know of a specific problem scenario, such as users leaving the terminal, we should rather introduce a dialog timeout, than an event. Or the specific scenario should be dealt with, by telling the user not to leave quite yet or by raising events in the scenario where the problem is.

We'd much rather understand the problems and deal with them, than to introduce events left, right and center in the entire product. On that basis, we won't introduce the events requested.

**Closed by JesperSchulz** 2024-01-23 13:33 UTC
Labels: event-request
