### ISSUE TITLE
[Bug] OnAfterEmailSentSuccesfully doesn't provide latest version of the "Email Item"

### ISSUE THREAD

**Issue by wdet** [microsoft/ALAppExtensions#5732] opened 2020-01-24 10:08 UTC
When you sent a document via email then an email dialog opens. In this dialog you have the possibility to change information like the To address for example.
In the OnAfterEmailSentSuccesfully event you don't receive this change, the provided "Email Item" still has the old value.

**Comment by wdet** [comment] 2020-02-25 10:19
Do you have any status update on this, please?

**Comment by AlexanderYakunin** [comment] 2020-04-08 07:20
Please be more detailed. We may not understand your issue, if you need to update TempEmailItem before send, you probably need to use this event 

            IsHandled := false;
            OnBeforeSendEmail(TempEmailItem, IsFromPostedDoc, PostedDocNo, HideDialog, ReportUsage, EmailSentSuccesfully, IsHandled);
            if IsHandled then
                exit(EmailSentSuccesfully);

**Comment by wdet** [comment] 2020-04-16 08:42
I have added the following subscriber to OnAfterEmailSentSuccesfully

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Document-Mailing", 'OnAfterEmailSentSuccesfully', '', false, false)]
local procedure OnAfterEmailSentSuccesfully(var TempEmailItem: Record "Email Item" temporary; PostedDocNo: Code[20]; ReportUsage: Integer)
begin
    Message(TempEmailItem."Send to");
end;
```

I try to send a posted invoice via mail. I do this by navigating to the posted sales invoices and then send a mail via "Print/Send" => Send....

I confirm the next dialog with these settings.
![image](https://user-images.githubusercontent.com/36985016/79431057-30f97e80-7fca-11ea-9303-be3dca3611b2.png)

After this, the email dialog opens.
![image](https://user-images.githubusercontent.com/36985016/79432346-f690e100-7fcb-11ea-9f3e-1c79d0458bce.png)


In this window I change the To email address to another valid address and send the mail.
The message shows the old email address instead of the new entered one.

**Comment by daansaveyn** [comment] 2020-05-26 08:04
I've just tested this on BC 16.1 and this is still not working properly. The "old" version of the Email Item is retrieved. When will this be fixed?

**Comment by AlexanderYakunin** [comment] 2020-06-05 08:48
I think this is currently By Design, as TempEmailItem is only temporary table to pass parameters to Mail sending process and there is no easy way to return changed data back. So this is not a problem of existing event, but more deeper design question. I will forward this ask to another team focused on EMailing story.

**Comment by JesperSchulz** [comment] 2020-06-18 08:53
We are currently redoing our email story, to be released with the next major. This issue will be considered in the new implementation.

**Closed by JesperSchulz** 2020-06-18 08:53 UTC
Labels: event-request
