### ISSUE TITLE
Event request cod90 OnBeforePostCombineSalesOrderShipment

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#2897] opened 2019-06-18 10:20 UTC
Can the OnBeforePostCombineSalesOrderShipmentpublisher be added to codeunit:90:"Purch.-Post"?

code:
[Modified.txt](https://github.com/microsoft/AL/files/3301050/Modified.txt)
[Original.txt](https://github.com/microsoft/AL/files/3301051/Original.txt)

**Comment by AlexanderYakunin** [comment] 2019-06-20 09:06
Closed as duplicate of #2898

**Closed** 2020-05-27 19:42 UTC
Labels: event-request
