### ISSUE TITLE
SalesLine.MaxQtyToShipBase breaks extensibility and is pretty dangerous

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#15567] opened 2021-12-17 09:21 UTC
Hi,

around June (in BC 18.3) the following function `MaxQtyToShipBase` was introduced on table `Sales Line` which is used in several places when posting (among others):
````
    procedure MaxQtyToShipBase(QtyToShipBase: Decimal): Decimal
    begin
        if Abs(QtyToShipBase) > Abs("Outstanding Qty. (Base)") then
            exit("Outstanding Qty. (Base)");

        exit(QtyToShipBase);
    end;
````

This function is pretty dangerous imho because essentially the `"Qty. to Ship (Base)"` is being recalculated while completely ignoring the value in `"Qty. to Ship"`.

In fact: we ran into a serious problem because one of our apps changes the `"Qty. to Ship"`. Through it's default OnValidate code, everything is updated accordingly. But then during posting the value in `"Qty to Ship (Base)"` is changed by this function without changing `"Qty. to Ship"` and we now have documents with diverging quantities and wrong item entries.

Please review this code. It is imperative that these kind of changes are made with caution. We can only test so much trough automated tests, but posted documents with misaligned quantities is **not** something we should be needing to test for.

**Comment by JesperSchulz** [comment] 2021-12-17 10:12
We're looking into your issue and will get back to you as soon as we can!

**Comment by hemisphera** [comment] 2022-01-18 07:18
Hi @JesperSchulz,

any update on this? You wanted to get back to me but I haven't heard from you since. I'm asking because we ran into yet another similar (if slightly different) issue that seems to stem from the same "Quantity-vs-QuantityBase-Balancing" change. This time though we were unlucky and had no event to use for bypassing it, forcing us into a very dirty workaround to get things working again.

We require you to give us some more insight and add some events (and maybe even consider a redesign), allowing us a fine-grained control over the whens and hows of these checks.

**Comment by JesperSchulz** [comment] 2022-01-21 11:13
I intentionally didn't write "_I_ will look into" but "_We're_ looking into" - not because I am royalty, but because I forwarded your issue to the team responsible for the code changes you commented on. Sometimes, that's all I can do as I don't have the right background to comment on the changes other teams made. I hoped the owning team would have picked up your request by now (I saw it got tagged) and would have gotten back to you, when processing it. But it does not look as if this case has been picked up yet - hence no update here. That's of course unfortunate and I'll try to ping the team again to see, if they have capacity to look into your issue.

I feel that I need to set expectations (again) though, when it comes to reporting issues here on GitHub: please be aware, that not all engineers are comfortable in engaging in public discussions, such as this one. I can _try_ to find someone to comment on the cases reported here, but there is no guarantee. Most importantly though, this repo is for **extensibility requests and issues** (like: I cannot write this and that extension, because this or that is missing/not working - issues of the none-time-critical kind). **It is NOT for reporting true production issues and product defects.** The second you have issues, which are time critical and/or which corrupt customer data or processes, please log the issue as a proper bug, to ensure that the right teams will deal with this defect within our SLAs for all of our supported versions. This is important to understand!

Product Defect with customer impact -> Log a proper bug in the proper channels to ensure it gets fixed within SLAs in all supported versions

Issue with extension development / request for extensibility points / comments on extensibility (which I mistakenly thought this was) -> Log an issue here and we'll try to find a solution for you, though without guarantee of any sort for timing or result

In your case, it now sounds as if you're more in the "product defect" category and you should probably file a proper product defect. Sorry for the long "lecture", but it is important that we align on the expectations you can have, when using one way of reporting over the other.

**Comment by adobriansky** [comment] 2022-01-24 08:35
Hi @hemisphera ,

Let me explain what this fix was about. The problem was in imbalance between quantity and base quantity caused by rounding precision.
Say, 1 bucket of an item contains 5.55555 kg. Receiving 0.3 buckets must post 1.666665 kg, but the base quantity is rounded up to 1.66667 kg. Post 0.3 bucket and 1.66667 kg again. Now we've received 0.6 buckets and 3.33334 kg. It leaves us to post 1 - 0.6 
= 0.4 buckets and 5.55555 - 3.33334 = 2.22221 kg. However, the remaining 0.4 buckets are precisely 2.22222 kg. The user receives the error message that they cannot post more than 2.22221 kg and gets stuck. That's why I limited base quantity to ship with base outstanding qty.

My understanding that you're running into a case when the correction of base quantity is greater than the rounding precision, and the difference between quantity and base quantity becomes visible. I'd be appreciated if you gave me steps to reproduce your issue or described the scenario when the MaxQtyToShipBase caused the imbalance.

**Comment by AlexanderYakunin** [comment] 2023-06-02 05:59
Closing as this is very old request without traction. Please create support ticket if you still have an issue

**Closed by AlexanderYakunin** 2023-06-02 05:59 UTC
Labels: extensibility-bug, missing-info
