### ISSUE TITLE
Codeunit 5763 Suppress commit 

### ISSUE THREAD

**Issue by KReinmann** [Microsoft/ALAppExtensions#923] opened 2019-01-24 09:25 UTC
Hello,

for external use, we nee a function SetSuppressCommit() in Codeunit 5763, which will avoid commits, if the global variable is set. 

Thanks and best regards,
K.

**Comment by grobyns** [comment] 2019-01-29 10:51
Hi,

I'm closing this issue as it is a duplicate of #695 

br/Gert

**Closed by grobyns** 2019-01-29 10:51 UTC
Labels: duplicate, extensibility-bug
