### ISSUE TITLE
Report Selection Usage Enum not extended

### ISSUE THREAD

**Issue by anwar0206** [microsoft/ALAppExtensions#10073] opened 2020-11-26 03:36 UTC
**Describe the bug**
After extending the "Report Selection Usage" enum. The new values are not shown on the Report Selection Page.

**To Reproduce**
Steps and to reproduce the behavior:
1. Create a file in AL for extending the "Report Selection Usage" enum
enumextension 70000 "My Report Sel Usage" extends "Report Selection Usage"
{

    value(70000; "SO Ship Rec")
    {
        Caption = 'Sales Order Shiping Records';
    }
    value(70001; "S.Inv Ship Rec")
    {
        Caption = 'Sales Inv Shiping Records';
    }

2. Publish the App
3. Use Tell me feature and search "Report Selection - Sales" or "Report Selection - Purchase"
4. click on Usage dropdown list.
}

``` AL Code to reproduce the issue ```

**Expected behavior**
After extending the enum, it should be displayed in the list.

**Screenshots**

**5. Versions:**

 - AL Language: 

 - Business Central:

**Comment by AlexanderYakunin** [comment] 2020-12-02 06:45
This is duplicate of #10059

**Comment by AlexanderYakunin** [comment] 2020-12-09 08:47
#10059 closed. Also closing this one.

**Closed by AlexanderYakunin** 2020-12-09 08:47 UTC
Labels: enum-request
