### ISSUE TITLE
Layout RDLC rep. 1322 "Standard Purchase - Order" is Empty

### ISSUE THREAD

**Issue by lorenzobuiatti** [microsoft/ALAppExtensions#19352] opened 2022-07-22 07:47 UTC
Hi,
RDLC file for the std report 1322 "Standard Purchase - Order" is Empty. 

If you export layout from BC365 v20 CU02 
![image](https://user-images.githubusercontent.com/86967009/180390046-18d0a3fa-2ade-4fbc-840c-d33683f98a1e.png)

Or check in file's folder BC365 v20 CU03
![image](https://user-images.githubusercontent.com/86967009/180390276-146db065-d319-4698-a524-f8bf6c170005.png)

thanks

**Comment by AlexanderYakunin** [comment] 2022-07-23 10:11
This is not related to extensibility, so I'm closing this request. You can report it to technical support if you really need fix here. 
I also see that this report is designed as DOCX, so this is probably by design.

**Closed by AlexanderYakunin** 2022-07-23 10:11 UTC

**Comment by lorenzobuiatti** [comment] 2022-07-25 07:50
Hi Alexander, thanks for the quick reply.
Is there a url/form/email for tecnical Support?
All "Standard Reports" have two layouts: RDLC and WordLayout (look for example rep.1302..1309) In the 1322 report they have forgotten the rdlc. 

Thanks.

**Comment by AlexanderYakunin** [comment] 2022-07-25 07:54
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .

Anyway, if you still think this is a bug, please reach out to the relevant support channels as specified in Product Support.
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	Online – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
