### ISSUE TITLE
API Page - DelayedInsert Error

### ISSUE THREAD

**Issue by MatDDev** [microsoft/ALAppExtensions#20522] opened 2022-10-04 10:25 UTC
Hey,

When I create a new API Page and set InsertAllowed to False, I would like to delete the DelayedInsert property, but the compiles yells at me, even though it should according to the error message.

![APIPageError](https://user-images.githubusercontent.com/13900033/193796143-95219fe2-0ad1-4fa2-b484-75204d9ead5d.png)

I am using the latest AL Language extension - v10.0.687650

**Comment by dnpb** [comment] 2022-10-04 13:14
Wrong repo, and duplicate of https://github.com/microsoft/AL/issues/7145 :-)

**Closed** 2022-10-04 18:23 UTC
