### ISSUE TITLE
Make Posting Buffer tables Extensible

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/ALAppExtensions#749] opened 2019-01-07 10:11 UTC
Buffer tables used in posting are not extensible.

Example: Table 49 - Invoice Post. Buffer.

By Adding a GUID field to these tables and putting that field last in Primary Key these tables should be extensible.

**Comment by ikoletic** [comment] 2019-01-09 15:10
Seems like this is a duplicate of this [idea](https://experience.dynamics.com/ideas/idea/?ideaid=1935a4ff-b040-e811-a822-0003ff68bbc0) and following conversation on [yammer](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1216893407).

**Comment by gunnargestsson** [comment] 2019-01-09 15:50
Agreed.  By adding the GUID field we will be able to post-by-description from purchase lines.

**Comment by ikoletic** [comment] 2019-01-09 16:00
Guess, we can close this one then?

**Comment by gunnargestsson** [comment] 2019-01-09 20:03
Yes, we can. I need the group by description option as mentioned in the comments on Yammer.

**Closed** 2019-01-10 09:06 UTC
Labels: extensibility-enhancement
