### ISSUE TITLE
[GlobalRequest] Table167 "Job".SetHideValidationDialog

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#18804] opened 2022-06-22 10:33 UTC
//------------------------------------------------------------RemoveInternal:BEGIN
internal procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
//------------------------------------------------------------RemoveInternal:END
begin
    HideValidationDialog := NewHideValidationDialog;
end;

**Comment by pri-kise** [comment] 2022-06-22 10:59
Duplicate of https://github.com/microsoft/ALAppExtensions/issues/18367

**Comment by AlexanderYakunin** [comment] 2022-06-23 07:44
Already done

**Closed by AlexanderYakunin** 2022-06-23 07:44 UTC
