### ISSUE TITLE
Extend Sent E-Mails functionality by Date

### ISSUE THREAD

**Issue by Hilbekale** [microsoft/ALAppExtensions#25698] opened 2024-01-12 10:34 UTC
### Describe the request

A variable named "NewerThanDate" is set in OnOpenPage trigger of Page 8883 "Sent Emails" of the System Application App. This is set to -30D:

`NewerThanDate := CreateDateTime(CalcDate('<-30D>', Today()), Time());`

However there is not any good way to modify that date before opening up the page, because most of the functions, tables, etc. are protected or internal. 

Therefore i would like to request that you add an overloaded function in codeunit 8901 "Email" "OpenSentEmails" which has the following parameters:

`procedure OpenSentEmails(RecordVariant: Variant; DateFilter: Text)`

The function should forward the datefilter and specify a manual date filter on the NewerThanDate in Page 8883 which will be opened by the function OpenSentEmails.

### Additional context

This is needed because we would like to show all sent e-mails for a document as field in the document pages:

![image](https://github.com/microsoft/ALAppExtensions/assets/25719407/032ef5f4-3a23-47c3-9d4a-dd0ccbd9bc0c)

We need the possibility to change the date filter In order to achieve this. Otherwise a lookup/drilldown into the details will show a filtered list which does not show all E-Mails for this specific document. 

Thanks.

**Comment by pri-kise** [comment] 2024-01-12 14:32
This is duplicate of https://github.com/microsoft/BCApps/issues/430

**Comment by JakovljevicDusan** [comment] 2024-01-15 14:19
@pri-kise, thanks for linking.
Closing this one as a duplicate.

FYI @JesperSchulz

**Closed by JakovljevicDusan** 2024-01-15 14:19 UTC
