### ISSUE TITLE
Unexpected error when using case with dates

### ISSUE THREAD

**Issue by acicatech** [microsoft/ALAppExtensions#16136] opened 2022-02-01 11:28 UTC
When using dates on case switch , object (table) will crash in runtime even if code is not executed.

To play it just create a new table object and add a procedure with a switch case with dates comparison , and run the table.

Example

`table 50001 CaseErrorTable
{
    DataClassification = ToBeClassified;
    
    fields
    {
        field(1;Id; Integer)
        {
            DataClassification = ToBeClassified;            
        }
    }
    
    keys
    {
        key(Key1; Id)
        {
            Clustered = true;
        }
    }
    local procedure Test()
    var
        CurrDate: date;
    begin
        case CurrDate of
            0D:
                Message('blank');
            else
                Message('not blank');
        end;
    end;   
}`

**Comment by dannoe** [comment] 2022-02-01 11:45
Duplicate of https://github.com/microsoft/AL/issues/6912

It is also the wrong repository. https://github.com/microsoft/AL would be correct.

**Closed** 2022-02-18 08:48 UTC
