### ISSUE TITLE
[Event Request] Codeunit 86 Sales-Quote to Order - OnBeforeInsertSalesOrderHeader at the right position

### ISSUE THREAD

**Issue by elweilando** [Microsoft/ALAppExtensions#77] opened 2018-10-19 07:19 UTC
In Codeunit 86 "Sales-Quote to Order" is the OnBeforeInsertSalesOrderHeader call at the wrong place. 
It fires before the SalesOrderHeader.Modify at line 86.
But the event should fires at line 73 before SalesOrderHeader.Insert(true).

Without this Event Request at the right position, you can't set another no.-series to the order for example.

It's completely confusing, if there is an event for OnBeforeInsert although the event fires OnBeforeModify

**Comment by AlexanderYakunin** [comment] 2018-10-30 13:50
This is by design, we cannot change it due to compatibility issue.

**Comment by JesperSchulz** [comment] 2019-01-16 08:31
Closing issue as per @AlexanderYakunin's reply.

**Closed by JesperSchulz** 2019-01-16 08:31 UTC
Labels: event-request
