### ISSUE TITLE
Error to print trial balance business central version 21.0.46256.46853 report 6

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#20784] opened 2022-10-28 10:51 UTC
Hello, 
when I try to print a trial balance, with balance at date <>0 as filter, the error appear: 

The supplied column ID '34' cannot be found in the query

Thanks,

**Comment by dnpb** [comment] 2022-10-28 11:22
Duplicate of https://github.com/microsoft/AL/issues/7224 but I don't think it's on-topic at either location. As a runtime/platform/application issue, it should be reported to MS via Support/Partner, not on GitHub.

**Comment by AlexanderYakunin** [comment] 2022-10-31 17:12
Please report bugs via Support/Partner, GitHub is for extensibility issues only. This particular issue is already reported, and fix is in progress.

**Closed by AlexanderYakunin** 2022-10-31 17:12 UTC
