### ISSUE TITLE
Shopify Events are not accessible

### ISSUE THREAD

**Issue by CorpitalFDP** [microsoft/ALAppExtensions#19667] opened 2022-08-03 08:52 UTC
All event codeunits in Shopify has "Access = Internal;" and is defined as "[InternalEvent(false)]"

Please give us access to the events in codeunit 30115, 30154, 30162, 30177, 30192,30196 and 30200.

All tables also have "Access = Internal;". Please remove this for at least tables used as parameters in the events in above codeunits.

**Comment by pri-kise** [comment] 2022-08-03 09:25
@CorpitalFDP  Please check the following yammer post of @AndreiPanko .
https://www.yammer.com/dynamicsnavdev/threads/1762140027789312

> As source code of Shopify Connector is on GitHub we would like to reuse pattern we have for System App:
> 
> Prioritize submitting improvement over extensibility.
-  For example, if your customer needs to export multiple translations of a product to Shopify, instead of asking for making some objects extensible – submit PR that implements this feature.
- If extensibility is really necessary – for example to orchestrate multiple extensions dealing with various sales channels – please create PR directly. Remember to write the proper justification of scenario.
>
> We will not process extensibility requests for connector registered as Issues on GitHub.

Duplicate of similiar issues: https://github.com/microsoft/ALAppExtensions/issues/18681, https://github.com/microsoft/ALAppExtensions/issues/18680

**Comment by AlexanderYakunin** [comment] 2022-08-07 16:07
See above, closing

**Closed by AlexanderYakunin** 2022-08-07 16:07 UTC
