### ISSUE TITLE
[Bug]: BCPT did not find any Docker Container

### ISSUE THREAD

**Issue by m3koenig** [microsoft/ALAppExtensions#26596] opened 2024-06-03 06:38 UTC
### Describe the issue

I want to use the Business Central Performance Toolkit VSCode Extension with a docker container but it did not find any container.
This will fetch forever and to type it in, will also not work.
![image](https://github.com/microsoft/ALAppExtensions/assets/9989457/bfcc7b43-cd39-4d56-9b6a-43949816a9d2)

### Expected behavior

List my Container.

### Steps to reproduce

1. Create a Docker Container with Performance Toolkit in it
2. run "BCPT: Setup new Business Central Performance Tooolkit project" command in VS Code:
![image](https://github.com/microsoft/ALAppExtensions/assets/9989457/8a1f4fae-1609-432f-b63c-8f4700f10272)
3. Select "Docker" and wait....

### Additional context

Did I miss some needed setup?
I tries serveral container parameters:
- OnPrem
- SandBox as OnPrem
- With Dev. License
- Without Dev. License
- and some others I forget.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by ChethanT** [comment] 2024-06-03 08:58
@m3koenig, can you give full details about the steps you followed, like how you got the docker image, version, parameters used to create a docker instance, etc, to help me repro the issue?
There are also few blogs that I hope you have already visited, if not please consider doing so. Fx. https://www.bertverbeek.nl/blog/2022/12/01/visual-studio-code-and-the-performance-toolkit/
https://demiliani.com/2023/09/05/dynamics-365-business-central-using-the-performance-toolkit-to-discover-performance-regressions/

**Comment by m3koenig** [comment] 2024-06-05 06:46
First, with this container creation script, I create the container:

```PowerShell
$containerName = 'MyBCPT'
$credential = Get-Credential -Message 'Using UserPassword authentication. Please enter credentials for the container.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'de' -select 'Latest'

New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -memoryLimit 8G `
    -includeTestToolkit `
    -includePerformanceToolkit -updateHosts
```

Then I open a VSCode BC Project (the code of an app) and run "BCPT: Setup new Business Central Performance Tooolkit project" command in VS Code:
![Command](https://private-user-images.githubusercontent.com/9989457/335961675-8a1f4fae-1609-432f-b63c-8f4700f10272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzAwNDYsIm5iZiI6MTcxNzU2OTc0NiwicGF0aCI6Ii85OTg5NDU3LzMzNTk2MTY3NS04YTFmNGZhZS0xNjA5LTQzMmYtYjYzYy04ZjQ3MDBmMTAyNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMDY0MjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRmMjlkMWI5NzZmNDYyYThmZjdiMzM0OTBkMDk0OTNlMTU0ZDU3NzQyMGEyYWI3ZWQyNDAxMDk5OWM5ZDZkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FxovQhpMeIm63oY7bhlqh-aOdhzhHONwf-XQoKup1wI)

Select "Docker" and then I waited:
![Waiting for the container](https://private-user-images.githubusercontent.com/9989457/335961267-bfcc7b43-cd39-4d56-9b6a-43949816a9d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzAwNDYsIm5iZiI6MTcxNzU2OTc0NiwicGF0aCI6Ii85OTg5NDU3LzMzNTk2MTI2Ny1iZmNjN2I0My1jZDM5LTRkNTYtOWI2YS00Mzk0OTgxNmE5ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMDY0MjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZiZGFhZmY3NmE3ZTZhY2U3MzYxYzM2YTNlOTI2NGYyZmQ1NDY5MDAwYmNlYTNhY2NmMmJiZTQ2NGVhMmM2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EDB9EsuDmS3PPL2YfjXdRzq4Zwavs5iWaT9K9TFGskM)

**Comment by vjekob** [comment] 2024-09-16 09:11
+1 for this. No operation with Docker selected actually works (running either). Tried on two different machines, latest version of Docker used.

**Comment by JesperSchulz** [comment] 2024-09-30 10:06
Same issue as #26799.

**Comment by ChethanT** [comment] 2024-10-01 11:12
This seem to have been caused by change in the BCArtifactUrl. Needs a new version of vsix

**Comment by JesperSchulz** [comment] 2024-11-04 14:19
I assume this was taken care of. Closing issue.

**Closed by JesperSchulz** 2024-11-04 14:19 UTC
Labels: bug, Integration

**Comment by sweikelt** [comment] 2024-11-22 09:17
don't think it was taken care of....still not working....we are waiting for weeks now :'(

**Comment by JesperSchulz** [comment] 2024-11-29 08:51
@ChethanT, could you check if this issue still is pending? Did we not resolve this?

**Comment by gggdttt** [comment] 2024-11-29 12:28
We have updated the BCArtifactUrl. But after testing the docker story of bcpt is still broken because of some changes in Admin endpoint. We are actively working on this but need more time to solve it. 

One option is using sandbox to run bcpt. It should work.

**Comment by gggdttt** [comment] 2024-12-18 11:45
Hi @sweikelt @m3koenig @vjekob  

We shall release a new version vsix to solve this. 

But I have one question to double check with you: Could you help me check if your docker's port 7086 is available?

![Image](https://github.com/user-attachments/assets/5dc2976e-aa67-4fbf-b92e-bc546f960935)

If it is not shown here, Consider to use this command to create the docker: 

`New-BcContainer `
     -accept_eula `
     -containerName $containerName `
     -credential $credential `
     -auth $auth `
     -artifactUrl $artifactUrl `
     -includeTestToolkit `
     -includePerformanceToolkit `
     -licenseFile $licenseFile `
     -updateHosts `
     -additionalParameters @('--expose 7086')`


This should be able to help you get rid of the issue temporary.

**Comment by sweikelt** [comment] 2024-12-18 13:31
@gggdttt, 

i tried it with a fresh container exposing port 7086 (my older ones didn't expose this port). 
Same like before - as Christian said

**Comment by gggdttt** [comment] 2024-12-18 14:09
Thanks for testing.  Looks like it is necessary to update the vsix. Our release pipeline is freeze for holiday. I shall release a new version of vsix asap. (Around the beginning of Jan).

**Comment by arsag** [comment] 2025-03-25 15:10
@gggdttt Is this issue solved? I tried with docker container - the same issue exists even with port 7086 open. Fetching forever.
