### ISSUE TITLE
[Reference Parameter Request] Codeunit 12 Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#6281] opened 2020-02-28 14:50 UTC
Hi,

could you change reference type to TRUE of Record "Gen. Journal Line" in all following procedure in Codeunit 12:

--local procedure **InsertDtldCustLedgEntry**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; var DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; Offset: Integer)

--local procedure **InsertDtldVendLedgEntry**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; var DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; Offset: Integer)

--local procedure **PostDtldCustLedgEntry**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; var AdjAmount: array[4] of Decimal)

--local procedure **PostDtldCustLedgEntryUnapply**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; OriginalTransactionNo: Integer)

--local procedure **PostDtldVendLedgEntry**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; var AdjAmount: array[4] of Decimal)

--local procedure **PostDtldVendLedgEntryUnapply**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; OriginalTransactionNo: Integer)

--local procedure **InsertDtldCustLedgEntryUnapply**(**GenJnlLine: Record "Gen. Journal Line"**; var NewDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; OldDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var NextDtldLedgEntryNo: Integer)

--local procedure **InsertDtldVendLedgEntryUnapply**(**GenJnlLine: Record "Gen. Journal Line"**; var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; OldDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var NextDtldLedgEntryNo: Integer)

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeInsertDtldCustLedgEntry**(var DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; **GenJournalLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer")

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeInsertDtldCustLedgEntryUnapply**(var NewDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; **GenJournalLine: Record "Gen. Journal Line"**; OldDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry")

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeInsertDtldVendLedgEntry**(var DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; **GenJournalLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer")

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeInsertDtldVendLedgEntryUnapply**(var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; **GenJournalLine: Record "Gen. Journal Line"**; OldDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeCreateGLEntriesForTotalAmounts**(var InvoicePostBuffer: Record "Invoice Post. Buffer"; **GenJournalLine: Record "Gen. Journal Line"**; GLAccNo: Code[20])

--[IntegrationEvent(false, false)]
    local procedure **OnBeforeCreateGLEntriesForTotalAmountsUnapply**(DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var CustomerPostingGroup: Record "Customer Posting Group"; **GenJournalLine: Record "Gen. Journal Line"**; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary)

--local procedure **PostDtldCVLedgEntry**(**GenJnlLine: Record "Gen. Journal Line"**; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; AccNo: Code[20]; var AdjAmount: array[4] of Decimal; Unapply: Boolean)

**Comment by RomanZanizdra** [comment] 2020-03-17 14:45
hi @Halilovast . What is the reason of your ask, what result do you finally want to get?

**Comment by Halilovast** [comment] 2020-03-17 14:57
Hello @RomanZanizdra ,
 in our Bulgarian Localization we generate some addional G/L Entry for some types of detailed CV Ledeger Entries. And we use some extended fields of T81 for this.

**Comment by RomanZanizdra** [comment] 2020-03-17 15:47
@Halilovast , ok. 
Do I understand correctly that you asks for a VAR for GenJnlLineLine parameter and how it will help in your solution?

**Comment by Halilovast** [comment] 2020-03-17 16:26
Yes, exactly. I need a VAR for GenJnlLineLine parameter.
Thank you.

**Comment by RomanZanizdra** [comment] 2020-03-18 15:06
hi @Halilovast . I'm afraid we cannot pass GenJnlLine as VAR in requested functions for now. 
First, actually it doesn't have sense because genjnlline is not updated in these functions and second, I don't understand the relation between VAR and solution described by you.

**Comment by Halilovast** [comment] 2020-03-18 16:10
hi @RomanZanizdra. So we have a big problem :(.  I solved my case in Business Central 14 (with dev env. - because there I can change standard objects) and I think this is not so difficult to release. 

Ok, I'll try to explain. In codeunit 12 all functions that I need are LOCAL. And all functions pass General Journal Line. For my cases I added some extended fields in T81. For example:
![image](https://user-images.githubusercontent.com/34268528/76978581-8f85fb00-693f-11ea-8c4d-49249728e74a.png)

In your answer "genjnlline is not updated in these functions" - but I update my fields with IntegrationEvent function and I can't pass it to another event function. 
![image](https://user-images.githubusercontent.com/34268528/76981572-754e1c00-6943-11ea-9166-136489a691b2.png)
 
And this is just one case, we have many. I realy need referance TRUE for table General Journal Line.

**Comment by RomanZanizdra** [comment] 2020-03-18 16:47
@Halilovast , why just you can't fill these fields in PostDtldCVLedgEntry for example or even before posting at all?

**Comment by Halilovast** [comment] 2020-03-18 17:32
Can you explain to me how to access DtldCVLedgEntry fields in [EventSubscriber] to IntegrationEvent procedure OnBeforeInsertGLEntryBuffer and create second entry depending on DtldCVLedgEntry."Entry Type"? 

       OnBeforeInsertGLEntryBuffer(TempGLEntryBuf, GenJnlLine,
          BalanceCheckAmount, BalanceCheckAmount2, BalanceCheckAddCurrAmount, BalanceCheckAddCurrAmount2, NextEntryNo);

**Comment by RomanZanizdra** [comment] 2020-03-18 17:49
From my point you don't need to subscribe for OnBeforeInsertGLEntryBuffer  in order to insert extra G/L Entry. You can do this from PostDtldCVLedgEntry before/after events having detailed buffer as parameter with entry type.
Finally functions CreateGLEntry, InitGLEntry, InsertGLEntry are global, you can use them if required.

**Comment by Halilovast** [comment] 2020-03-18 17:59
what is the problem? I beleave make this parameter with referance is so easy, this is one of my many requests for referance, and has not been a problem so far . I spent a lot of time for our localization, which Microsoft does not do, now and does not help us.

**Comment by RomanZanizdra** [comment] 2020-03-19 06:06
Hi @Halilovast . There are no any problems. I've just tried to explain you why the request is not fully correct. From my point of view you are trying to use wrong places/subscribers for localization and follow from your example you just need to subscribe to other subscriber leaving your code the same. Anyway you can ask question on community site how to adjust your solution.

**Comment by RomanZanizdra** [comment] 2020-03-20 10:38
hi @Halilovast . Can we close this issue?

**Comment by Halilovast** [comment] 2020-03-20 10:41
hi @RomanZanizdra , not yet, please.
My colleague will join here and he'll try to explain. because these chages is important to us :(

**Comment by AlexanderYakunin** [comment] 2020-03-22 08:11
We cannot simply add VAR for existing events anymore, this is confirmed to be breaking change for many extensions. We are going to use interfaces for implementing such scenarios going forward, I'd recommend you find another solution for time being, like Roman advised above.

**Comment by Halilovast** [comment] 2020-03-22 19:27
Ok, I did two test cases.

First one:
If I try to use IntegrationEvent from Codeunit 80, which has parameter without a reference (without VAR) and add VAR in my code, I receive an error.

    
    [IntegrationEvent(false, false)]
    local procedure OnAfterDeleteAfterPosting(SalesHeader: Record "Sales Header"; SalesInvoiceHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; CommitIsSuppressed: Boolean)
    begin
    end;

![image](https://user-images.githubusercontent.com/34268528/77253911-5c58aa00-6c66-11ea-9b21-ea4a8f95bd3b.png)


The second one:
I use IntegrationEvent from Codeunit 80, which has parameter with reference (with VAR) and use this parameter without VAR, there are no errors in the code and it works fine

    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforePostSalesDoc(var SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; PreviewMode: Boolean; var HideProgressWindow: Boolean)
    begin
    end;

![image](https://user-images.githubusercontent.com/34268528/77254117-b9089480-6c67-11ea-87a8-cc0b52f8da35.png)

![image](https://user-images.githubusercontent.com/34268528/77254189-3d5b1780-6c68-11ea-8889-3ed3cf845684.png)

These tests show that if you remove VAR from any of parameters in IntegrationEvent Procedure, which is used in many extensions, it will  break the code. I don't really want this from you.

What I asked was to add VAR, and if that is visible from the second example test, this will in no way interrupt the existing extensions.
It's very difficult to make changes with the current objects, especially when these changes relate to the posting function, because the basic parameter in Codeunit 12- Table 81 (Gen. Journal Line), is not accessible. And this is the parameter that transferred between the general functions.

**Comment by RomanZanizdra** [comment] 2020-04-20 06:43
Hi @Halilovast , sorry for a long break in discussion.
I understand what you are asking for (adding var is not a breaking change for now) and this is not difficult. The issue is that it doesn't make any sense except that it will be easier for you to localize or implement your solution. But as I mentioned above you are using not fully correct places for implementation. Can we somehow try to finalize this discussion and come to the acceptable end point?

**Comment by AlexanderYakunin** [comment] 2020-06-06 10:55
I'm closing this discussion. We are not going to make these kind of changes in Codeunit 12, instead you should use different design. There are many possibilities how this can be done, for example you can use temporary buffer table in your extension to share additional data between tables in Codeunit 12, you have no need to transfer all these fields across all tables, like you did in C/SIDE and all BaseApp.

**Closed** 2020-06-18 07:43 UTC
Labels: event-request, wontfix
