### ISSUE TITLE
Bug regarding reservations and orderplanning not in release (forgotten fix for V21)

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#20598] opened 2022-10-12 11:40 UTC
Dear Jesper Schulz,

on June 27 2022 you wrote that this issue would be resolved in the next major release:
https://github.com/microsoft/ALAppExtensions/issues/18815

Version 21 is going to be released, but I tested the bug in V21 preview, and it still is wrong. Please pick this up soon as possible. The orderplanning is still faulty. I canceled the reservation and it still noted it as planned false.
![image](https://user-images.githubusercontent.com/92578153/195333241-cba954b1-7b3e-48cc-9b13-12b43e5b9e59.png)

![image](https://user-images.githubusercontent.com/92578153/195333077-d674d5c8-ce16-4570-82cb-61351f768017.png)

![image](https://user-images.githubusercontent.com/92578153/195333422-e52f32c6-3deb-45b1-a356-efb945f27ebd.png)

As a side note to even help your developers even more:
In the Chronus the line is not set to planned in the first place. Because the quantity is 12 and reserved is 10.  I also tested what should happen if you change the quantity, from 12 to 10 while 10 is reserved on the line. Plannend kept saying false, which is wrong. This is because all quantities are reserved and there for it is plannend. Please take also this in consideration, while fixing the issue.

Build ID: 42833.

**Comment by AlexanderYakunin** [comment] 2022-10-12 11:58
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by JohnFrostDP** [comment] 2022-10-12 12:07
Dear Alexander,

I am fully aware of what you post, but your colleague Jesper wrote, and I quote from my last issue:
https://github.com/microsoft/ALAppExtensions/issues/18815

"If you have follow-up questions or requests, please create a new issue where you reference this one." 

So i did exactly that. If I need to walk another road please say so, but I am just doing what has been said earlier.

**Comment by AlexanderYakunin** [comment] 2022-10-12 12:10
Sorry, Jesper's comment was about process on GitHub only, not about content of request. It is waiting of you time to create hotfix requests here, as they won't be addressed.

**Comment by JohnFrostDP** [comment] 2022-10-12 12:21
Hi Alexander,

Well, if he would only be talking about github then he wouldn't write to refer to the last issue with a new issue now would he. He did also mean what he said a sentence before that. And I qoute again from my previous issue:

"We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues."

What he says is quite clear. There would be a fix in the next major release. This being V21. 

Once again, if you now conclude that i still need to walk another road please do say so. This is not to tease you, please help me understand what went wrong.

**Comment by JesperSchulz** [comment] 2022-10-12 12:31
Hi John,

I am sorry about the confusion. The message posted in #18815 wasn't posted by me personally, but by a bot. That message is posted, whenever we resolve an internal work item linked to a GitHub issue as completed. In this case, I am not certain why the bot chose to post this message, as your issue never should have been addressed as part of this initiative. We only accept issues related to extensibility, which do not have any timeline or urgency. We cannot accept bug reports, as we cannot guarantee, when we will get to address the issue, just as we will not ensure, that the issue is addressed in all supported versions of Business Central. If you have a product defect, which has direct customer impact, and which must be addressed within certain timeframe, please create a support request as outlined above.

I will investigate, why your issue 18815 was accepted in the first place, and which fix was provided, which again resulted in the automatically posted message. That was a mistake for which I apologize.

**Comment by JesperSchulz** [comment] 2022-10-12 12:40
This absolutely sounds like something we should fix! We just need to get your issue to the right team, which does this the right way and within the right SLAs. Here's the standard text, I usually close "non-extensibility" related issues with. Is there any chance you can follow those guidelines and get this issue reported the right place? Let me know if you need more help to get a support case opened!

_Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible._

_To open a support case, you can:_

- _Open a support request to CSS through the PartnerSource portal_
- _Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company_

_If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create._

_Thanks for reporting the issue.__

**Comment by AlexanderYakunin** [comment] 2022-10-19 09:43
I confirm we cannot fix it until this issue will be reported via technical support and hotfix requests will be created with proper repro steps and verification. Sorry for inconvenience, but extensibility team cannot make this fix anyway. Therefore, closing this request.

**Closed by AlexanderYakunin** 2022-10-19 09:43 UTC
