### ISSUE TITLE
[Enum Request] Table 77 Usage field

### ISSUE THREAD

**Issue by svwfr** [microsoft/ALAppExtensions#2011] opened 2019-04-08 11:57 UTC
Please convert Usage of Report Selections to an enum.

**Comment by Pieterheinevdm** [comment] 2019-05-23 10:17
please add this enum type also to the same usage field in table:9657:"Custom Report Selection"

**Comment by rvanbekkum** [comment] 2019-11-01 09:18
This seems like a duplicate of issue #260, which is marked as "ships-in-future-update".
Probably this one was created because #260 was closed at that time though.

Also, it seems this issue was mistakenly flagged as "event-request" ;).

**Comment by SteveKrisjanovsD365** [comment] 2020-01-06 21:16
Can we get an update on this enum request?

According to this closed issue https://github.com/microsoft/ALAppExtensions/issues/4901 the enum has been implemented, but I just downloaded 15.2 onprem and the Usage field is still an option.

**Comment by AlexanderYakunin** [comment] 2020-02-05 07:36
We do not implement enums to 15.X versions, this is breaking change. All enums available in new version.

**Closed by AlexanderYakunin** 2020-02-05 07:36 UTC
Labels: event-request
