### ISSUE TITLE
[FeatureRequest] QR Code .NET wrapper

### ISSUE THREAD

**Issue by NAVAXMiMa** [microsoft/ALAppExtensions#14138] opened 2021-08-30 13:23 UTC
Hi,

as QR codes are used in more and more use cases, such as printing bank information on invoices so that payments can be made by scan and so on. It would be interesting if Business Central would already have an integrated QR code generation out of the box. While looking for a solution I stumbled across that this was already done in the CH version with .NET wrapper classes - why isn't this also available in the AT or DE version or others?

Could you please make this available for the AT and DE version as well? 

I'm sure this will be needed all over the world, since almost all systems now work with QR codes.

https://github.com/microsoft/ALAppExtensions/blob/master/Apps/CH/SwissQRBill/app/src/dotnet.al

**Comment by db-bc** [comment] 2021-08-30 13:30
seems like a dupe of https://github.com/microsoft/ALAppExtensions/issues/13733

**Closed as completed** 2021-10-18 19:08 UTC
Labels: extensibility-enhancement, ships-in-future-update
