### ISSUE TITLE
[Event Request] Table 5050 Contact - OnBeforeAssistEdit

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#6883] opened 2020-04-29 09:34 UTC
Please add a new publisher event to the function `AssistEdit` as follows:
                
```
.
.
[External] AssistEdit(OldCont : Record Contact) : Boolean
 
//>> Start New Publisher Call
OnBeforeAssistEdit(Rec, OldCont, IsHandled, ExitValue);

IF IsHandled THEN
  EXIT(ExitValue);
//<< End New Publisher Call
 
WITH Cont DO BEGIN
  Cont := Rec;
  RMSetup.GET;
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnBeforeAssistEdit(VAR Contact : Record Contact;OldContact : Record Contact;VAR IsHandled : Boolean;VAR ExitValue : Boolean)
```

**Comment by StanPesotskiy** [comment] 2020-04-29 12:38
Already implemented. Duplicate of https://github.com/microsoft/ALAppExtensions/issues/4978

**Closed by StanPesotskiy** 2020-04-29 12:38 UTC
Labels: event-request

**Comment by aaugustijn** [comment] 2020-04-29 12:43
What if I want to return FALSE instead of the default TRUE which is specified in #4978?

**Comment by StanPesotskiy** [comment] 2020-04-29 13:13
You are right. I have missed it. This additional parameter will be added to the event.

**Comment by bc-ghost** [comment] 2020-04-30 09:17
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
