### ISSUE TITLE
Integration is Enabled in Cronus by Default Which is causing Blocking

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#5567] opened 2020-01-13 19:08 UTC
Integration is enabled by default in Cronus Database.  This is causing severe blocking on "Integration Record" table.  Integration needs to be turned off by default.  I believe this issue is reported back to Microsoft in the past since NAV2018.  But it is keep on coming on each release.  Can you please address it and fix it.  It is suggested to alter "OnGetIntegrationActivated" function in codeunit 5465 (Graph Mgt - General Tools) to only check and activate synchronisation only is IsSyncEnabled variable set and there are some records in ODataEdmType table.  See example below.  Currently Integration is simply enabled when there are some records in ODataEdmType table (which is the case in Cronus database).  The full suggested code is in the attachment.

         //DOC SQLTune -
        IF IsSyncEnabled THEN
         //DOC SQLTune +
          IsSyncEnabled := not ODataEdmType.IsEmpty;

**Comment by Rama-M** [comment] 2020-01-13 19:09
Can you please target this change as a hotfix and in the next release (release 2020) and all future release.

**Comment by nikolakukrika** [comment] 2020-02-18 12:52
The issue is resolved as won't fix.

The suggested code is wrong - IsSyncEnabled will always be false, so we will never set it to true.
We cannot change the current logic. There is an Event OnForceIsApiEnabledVerification that controls the proper check IsApiEnabled. Changing the logic of the method would break the event.
You can either subscribe to this method and set APIsEnabled to false on the server config, Subscribe to the codeunit 5150 and disable the integration or empty ODataEdmType table.

**Comment by Rama-M** [comment] 2020-02-19 10:38
Dear Microsoft,

Please remember, the requst is to ensure Integration is not turned on by default in Cronus database. The code change is only a suggestion from us. We Appreciate, it may not be the right solution. Can Microsoft work on a solution that out of the box (In cronus database) it is switched off.

Thanks

Rama Mathanmohan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexanderYakunin** [comment] 2020-02-19 14:04
As explained above we cannot make this change as it is breaking change for existing logic. You can do it for your solution if needed using events.

**Closed by AlexanderYakunin** 2020-02-19 14:04 UTC
Labels: extensibility-bug
