### ISSUE TITLE
Enqueue email not clear that if it is submitted in a transaction and error occurs all enqueued email is rolled back

### ISSUE THREAD

**Issue by tfbtrading** [microsoft/ALAppExtensions#11431] opened 2021-03-02 19:21 UTC
This may be a feature and not a bug. However, we had an issue recently in which a process running was encountering an error with a single customer record as part of a batch report being run. For two weeks we hadn't realised that this email wasn't going out as the person was sending the email was triggering the report, getting up and leaving and by the time they returned the business central web client had timed out as so error message was not shown. The only way to know that it failed was to see that email wasn't in sent email table - however there is no record of a failed enqueue task that was rolled back.

**Comment by JesperSchulz** [comment] 2021-03-03 13:33
Thanks for reporting. We're going to see if we can reproduce this issue on our end!

**Comment by darjoo** [comment] 2021-03-04 08:13
Hi @tfbtrading, could you provide the steps the user did to enqueue the email?

**Comment by tfbtrading** [comment] 2021-03-04 08:41
It’s myself Coa code in PTE we are running a report that itself generates out PDF and enqueues emails for a price list. I actually think the behaviour is fine. Rollback I mean. The issue is that as the session is timed out no error is seen on the screen and their is no log of what happened as it’s not associated with a job queue entry. It also didn’t show in last error info. Perhaps telemetry would show this error but I haven’t explored it and so operational issue was missed and I wouldn’t be the only one as in the past the smtp email was sent even if an error occurred.

Regards,

Russell Kallman
TFB Trading Australia
Landline: +61 3 9816 3444
Mobile: +61 408 440 663

(Sent from my mobile in a rush. Apologies in advance for any keyboard autocorrect errors)
________________________________

**Comment by darjoo** [comment] 2021-03-15 07:40
Sorry for the late reply as we have been busy with getting 18.0 ready.
As you mentioned, the behavior is by design (rolling back). If you'd like to ensure that the enqueued email stays, you could do a commit right after enqueuing the email.

The old smtp sending always sent in the current session, and if you'd like the same behavior, using the `Send` procedure in the Email codeunit would do that. `Enqueue` procedure queues it up in the background to be run later(asap).

I'm not sure what is causing your timeout issue, but that would clear the last error since it'd be in a new session when you refresh. But also as you mentioned, if there was an error, telemetry would show it :) 

I hope that helped. I'll close this bug but if you require more assistance, please reopen it.

**Closed by darjoo** 2021-03-15 07:40 UTC
Labels: foundation, question
