### ISSUE TITLE
Add event OnBeforeGetDocumentDate in "Purchase Line - Price" implements "Line With Price" 

### ISSUE THREAD

**Issue by a-augros** [microsoft/ALAppExtensions#25043] opened 2023-10-10 10:04 UTC
**🕮 Describe the request**

Since BC23 update have been done in codeunit 7021 "Purchase Line - Price" implements "Line With Price" that now longer allow to use Temporary records (Purchase Header) with defined date to calculate prices because of change in GetDocumentDate function

**Additional context**

A Workaround would be to add an event in codeunit 7021 "Purchase Line - Price" implements "Line With Price" 

```
    local procedure GetDocumentDate() DocumentDate: Date;
    begin
        **OnBeforeGetDocumentDate(DocumentDate, PurchaseHeader, PurchaseLine, IsHandled);
        if IsHandled then
            exit;**
        DocumentDate := PurchaseLine.GetDateForCalculations();
        OnAfterGetDocumentDate(DocumentDate, PurchaseHeader, PurchaseLine);
    end;

    **[IntegrationEvent(false, false)]
    local procedure OnAfterGetDocumentDate(var DocumentDate: Date; PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;**

```

**Comment by pri-kise** [comment] 2023-10-10 12:31
@a-augros wouldn't it be an approach to call the procedure `SetPurchHeader` before the procedure `GetDateForCalculations`.

@TKapitan could you maybe take a look at this issue?
i think it was caused by you're change for item references.
https://github.com/microsoft/BusinessCentralApps/pull/366

I guess the same problem occurs with temporary saleslines, too.

CC: @ChethanT , @JesperSchulz

**Comment by pri-kise** [comment] 2023-10-10 12:36
Temporary you could subscribe via manual binding to the event `OnBeforeGetPurchHeader` and inject the temporary purchase header there.

**Comment by a-augros** [comment] 2023-10-10 14:47
Thanks for support 

Subscribe via manual binding to the event OnBeforeGetPurchHeader works but it's a temporary solution, it would be better to get a fix for that because it can have an impact on other ISV.

For information I create also a support request on that topic (#2309250060003308)

**Comment by TKapitan** [comment] 2023-10-12 16:55
Hey @a-augros,
Maybe it can help to mention that there is a fix for this issue in https://github.com/microsoft/BusinessCentralApps/pull/472 in the support request. The base app contribution program is still in the pilot phase, so I'm not sure how well the support team is informed. 

Thanks again for pointing out this issue, I somehow forgot to think about the temp records (and I also have two app source apps that calculate prices using temp lines....... :D ).

**Comment by AlexanderYakunin** [comment] 2023-11-03 11:51
Please close this request if the issue is addressed.

**Comment by JesperSchulz** [comment] 2023-12-01 14:07
Assuming this is addressed due to missing response.

**Closed by JesperSchulz** 2023-12-01 14:07 UTC
Labels: extensibility-bug, event-request
