### ISSUE TITLE
Calls to Integration Event [OnAfterTransferRecordFields] have inconsistent parameters

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#22920] opened 2023-04-06 01:02 UTC
here is the procedure definition (in CU 5345 "Integration Rec. Synch. Invoke")

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferRecordFields(var SourceRecordRef: RecordRef; var DestinationRecordRef: RecordRef; var AdditionalFieldsWereModified: Boolean; DestinationIsInserted: Boolean)
    begin
    end;

Within the codeunit, it is referenced twice (21.5):

line 448:

    OnAfterTransferRecordFields(SourceRecordRef, DestinationRecordRef, AdditionalFieldsModified, true);

line 464:

    OnAfterTransferRecordFields(SourceRecordRef, DestinationRecordRef, AdditionalFieldsModified, SynchAction <> SynchActionType::Insert);

If the 4th parameter in the event is "DestinationIsInserted", why does line 464 call it as "SynchActionType <> SynchActionType::Insert" (with a not-equal-to operator)? Shouldn't it call it as "SnychActionType = SynchActionType::Insert" (with an equal-to operator)?

Additionally CU 5341 "CRM INt. Table. Subscriber" subscribes to the OnAfterTransferRecordFields event, and not sure if it knows this boolean seems to be backwards when subscribing to the event when called from line 464. So that may need to be evaluated also.

thanks.

**Comment by dcenic** [comment] 2023-05-01 19:13
This is by design. The 4th parameter of the event OnAfterTransferRecordFields is DestinationIsInserted. SynchActionType::Insert is the only synch action type in which the destination record is not already inserted, but is about to be inserted later, much after this event is raised.
The other place that you refer, line 448, where we set this parameter to true is in a method marked as Scope OnPrem, which means that it cannot be called from extensions. In BaseApp we call this method only from IntegrationTableSynch.CheckTransferFields public method, and in that method, we explicitly set synch action to ForceModify before we call it. Therefore, value DestinationIsInserted = true is fine here as well, because the synch action is not "Insert".

**Comment by grantbrimhall** [comment] 2023-05-01 20:45
Hi Thank you for looking into this ... so I should interpret DestinationIsInserted to mean Destination_WasAlready_Inserted?? as opposed to SyncActionType = SyncActionType::Insert?

**Comment by JesperSchulz** [comment] 2024-06-18 09:12
Closing as "By Design".

**Closed by JesperSchulz** 2024-06-18 09:12 UTC
Labels: extensibility-bug
